# Generated by Django 3.1.5 on 2021-04-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_centers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centers',
            name='center_phone',
        ),
    ]
